DROP TABLE IF EXISTS User
DROP TABLE IF EXISTS Post

CREATE TABLE User(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
)

CREATE TABLE Post(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT,
    body TEXT,
    FOREIGN KEY (author_id) REFERENCES User(id)
)
